// ----- PHOTO COMPRESSION -----
// Thumbnails = 50%+ (1024 max height) | Previews = 60%+ (max dimension of 8192)
const photoCollections = ["Featured Photos", "Bird Photography", "Wildlife Photography", "Macro Photography", "Landscape Photography", "Space Photography", "Nature Photography"];
const photos = [
{
	date:"2026-3-2",
	collections:["Featured Photos", "Bird Photography", "Wildlife Photography", "Nature Photography"],
	rating:4.5,
	title:"Pine Siskin",
	subject:"Pine Siskin (spinus pinus)",
	location:"Idaho, USA",
	shutterspeed:"1/160",
	aperture:"6.3",
	iso:"800",
	focallength:"600",
	camera:"Canon R5 Mark II",
	lens:"Sigma 150-600mm f5-6.3 (Contemporary)",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:4220,
	height:2769,
},
{
	date:"2026-3-1",
	collections:["Featured Photos", "Bird Photography", "Wildlife Photography", "Nature Photography"],
	rating:4,
	title:"Looking For Some Food",
	subject:"Black-capped chickadee (poecile atricapillus)",
	location:"Idaho, USA",
	shutterspeed:"1/160",
	aperture:"6.3",
	iso:"6400",
	focallength:"600",
	camera:"Canon R5 Mark II",
	lens:"Sigma 150-600mm f5-6.3 (Contemporary)",
	tags:["Handheld"],
	caption:`This little guy came so close to me that I couldn't even focus most of the time!`,
	filetype:"jpg",
	width:5384,
	height:3789,
},
{
	date:"2026-2-20",
	collections:["Featured Photos", "Wildlife Photography", "Macro Photography", "Nature Photography"],
	rating:4.5,
	title:"158MP Fly",
	subject:"",
	location:"Idaho, USA",
	shutterspeed:"1/30",
	aperture:"2.8",
	iso:"1000",
	focallength:"25",
	camera:"Canon R5 Mark II",
	lens:"Laowa 25mm f2.8 2.5-5X Ultra-macro",
	tags:["5X", "Focus Stacked (2,609)", "Stitched (2,609)"],
	caption:`This image took around 1 hour to capture and 5 hours to post-process.`,
	filetype:"jpg",
	width:15118,
	height:10425,
},
{
	date:"2026-2-11",
	collections:["Featured Photos", "Space Photography", "Nature Photography"],
	rating:4.5,
	title:"Portal to Heaven",
	subject:"Orion Nebula",
	location:"Idaho, USA",
	shutterspeed:"30",
	aperture:"6.3",
	iso:"1000",
	focallength:"600",
	camera:"Canon R5 Mark II",
	lens:"Sigma 150-600mm f5-6.3 (Contemporary)",
	tags:["Stacked", "Star Tracker Used"],
	caption:`This series of 125 photographs was taken from around 9:06-11:17PM PST.`,
	filetype:"jpg",
	width:4067,
	height:5223,
},
{
	date:"2026-1-26",
	collections:["Featured Photos", "Macro Photography"],
	rating:4.5,
	title:"Imprecise Precision",
	subject:"3/8\"-16 tripod head mounting bolt",
	location:"Idaho, USA",
	shutterspeed:"1/30",
	aperture:"2.8",
	iso:"100",
	focallength:"25",
	camera:"Canon R5 Mark II",
	lens:"Laowa 25mm f2.8 2.5-5X Ultra-macro",
	tags:["5X + extension tube", "Focus Stacked (99)"],
	caption:`A super smooth and precisely machined bolt doesn't look so precise at microscopic magnification!`,
	filetype:"jpg",
	width:7971,
	height:5261,
},
{
	date:"2026-1-18",
	collections:["Featured Photos", "Space Photography", "Nature Photography"],
	rating:4,
	title:"Celestial Paint",
	subject:"Orion Nebula",
	location:"Idaho, USA",
	shutterspeed:"30",
	aperture:"6.3",
	iso:"1250",
	focallength:"600",
	camera:"Canon R5 Mark II",
	lens:"Sigma 150-600mm f5-6.3 (Contemporary)",
	tags:["Stacked", "Star Tracker Used"],
	caption:`This series of 11 photographs was taken at around 9:45PM PST.`,
	filetype:"png/jpg",
	width:3169,
	height:4259,
},
{
	date:"2026-1-13",
	collections:["Featured Photos", "Bird Photography", "Wildlife Photography", "Nature Photography"],
	rating:4,
	title:"Aerial Hunter",
	subject:"Northern Harrier (circus hudsonius)",
	location:"Kootenai National Wildlife Refuge, Idaho, USA|https://maps.app.goo.gl/szayVDmieDm7BHsU8|48.731852, -116.398001",
	shutterspeed:"1/800",
	aperture:"6.3",
	iso:"2000",
	focallength:"600",
	camera:"Canon R5 Mark II",
	lens:"Sigma 150-600mm f5-6.3 (Contemporary)",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:3467,
	height:2312,
},
{
	date:"2026-1-11",
	collections:["Featured Photos", "Wildlife Photography", "Macro Photography", "Nature Photography"],
	rating:4.5,
	title:"Ladybug",
	subject:"",
	location:"Idaho, USA",
	shutterspeed:"1/80",
	aperture:"2.8",
	iso:"2000",
	focallength:"25",
	camera:"Canon R5 Mark II",
	lens:"Laowa 25mm f2.8 2.5-5X Ultra-macro",
	tags:["2.5X", "Focus Stacked (134)"],
	caption:``,
	filetype:"jpg",
	width:6913,
	height:4519,
},
{
	date:"2026-1-11",
	collections:["Featured Photos", "Wildlife Photography", "Macro Photography", "Nature Photography"],
	rating:3.5,
	title:"Not So Bad In Macro",
	subject:"Black stink bug (brochymena affinis)",
	location:"Idaho, USA",
	shutterspeed:"1/80",
	aperture:"2.8",
	iso:"400",
	focallength:"25",
	camera:"Canon R5 Mark II",
	lens:"Laowa 25mm f2.8 2.5-5X Ultra-macro",
	tags:["2.5X", "Handheld", "Focus Stacked (281)"],
	caption:`These guys sure are obnoxious and smell terrible but they look incredible in macro!`,
	filetype:"jpg",
	width:7058,
	height:4406,
},
{
	date:"2026-1-10",
	collections:["Featured Photos", "Wildlife Photography", "Macro Photography", "Nature Photography"],
	rating:4,
	title:"Cutely Intimidating",
	subject:"Jumping spider (pelegrina insignis)",
	location:"Idaho, USA",
	shutterspeed:"80",
	aperture:"2.8",
	iso:"400",
	focallength:"25",
	camera:"Canon R5 Mark II",
	lens:"Laowa 25mm f2.8 2.5-5X Ultra-macro",
	tags:["2.5X", "Handheld", "Focus Stacked (3)"],
	caption:`These guys sure don't like to sit still long enough for you to get a very good photo...`,
	filetype:"jpg",
	width:4688,
	height:3478,
},
{
	date:"2026-1-10",
	collections:["Featured Photos", "Macro Photography"],
	rating:5,
	title:"Window of the Soul",
	subject:"My eyeball",
	location:"Idaho, USA",
	shutterspeed:"60",
	aperture:"2.8",
	iso:"320",
	focallength:"25",
	camera:"Canon R5 Mark II",
	lens:"Laowa 25mm f2.8 2.5-5X Ultra-macro",
	tags:["2.5X", "Focus Stacked (10)"],
	caption:``,
	filetype:"jpg",
	width:8012,
	height:5083,
},
{
	date:"2026-1-9",
	collections:["Featured Photos", "Bird Photography", "Wildlife Photography", "Nature Photography"],
	rating:4,
	title:"Snack Secured",
	subject:"Black-capped chickadee (poecile atricapillus)",
	location:"Idaho, USA",
	shutterspeed:"1/640",
	aperture:"6.3",
	iso:"4000",
	focallength:"600",
	camera:"Canon R5 Mark II",
	lens:"Sigma 150-600mm f5-6.3 (Contemporary)",
	tags:["Handheld"],
	caption:`This chickadee looks so cute holding his <i>"prize"</i>!😄`,
	filetype:"jpg",
	width:5004,
	height:3328,
},
{
	date:"2025-12-27",
	collections:["Featured Photos", "Bird Photography", "Wildlife Photography", "Nature Photography"],
	rating:4,
	title:"Patiently Waiting",
	subject:"Black-capped chickadee (poecile atricapillus)",
	location:"Idaho, USA",
	shutterspeed:"1/500",
	aperture:"6.3",
	iso:"6400",
	focallength:"600",
	camera:"Canon R5 Mark II",
	lens:"Sigma 150-600mm f5-6.3 (Contemporary)",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:5686,
	height:3996,
},
{
	date:"2025-12-17",
	collections:["Featured Photos", "Bird Photography", "Wildlife Photography", "Nature Photography"],
	rating:4,
	title:"Standing Alone",
	subject:"Canada goose (branta canadensis)",
	location:"Saltese Flats Wetlands, Washington, USA|https://maps.app.goo.gl/GUetyq3ygLysqcrv5|47.628848, -117.137575",
	shutterspeed:"1/800",
	aperture:"6.3",
	iso:"250",
	focallength:"600",
	camera:"Canon R5 Mark II",
	lens:"Sigma 150-600mm f5-6.3 (Contemporary)",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:4405,
	height:6294,
},
{
	date:"2025-11-19",
	collections:["Featured Photos", "Space Photography", "Nature Photography"],
	rating:4.5,
	title:"Sand in the Sky",
	subject:"Milky Way galaxy",
	location:"Idaho, USA",
	shutterspeed:"30",
	aperture:"5",
	iso:"25600",
	focallength:"150",
	camera:"Canon R5 Mark II",
	lens:"Sigma 150-600mm f5-6.3 (Contemporary)",
	tags:["Star Tracker Used"],
	caption:`This photo was taken at around 10:10PM PST.`,
	filetype:"jpg",
	width:5464,
	height:8192,
},
{
	date:"2025-11-18",
	collections:["Featured Photos", "Bird Photography", "Wildlife Photography", "Nature Photography"],
	rating:4.5,
	title:"King of the Trees",
	subject:"Golden-crowned kinglet (regulus satrapa)",
	location:"Tubbs Hill, Idaho, USA|https://maps.app.goo.gl/LjXZSbNfWwUVFPuX7|47.667104, -116.771847",
	shutterspeed:"1/640",
	aperture:"6.3",
	iso:"6400",
	focallength:"600",
	camera:"Canon R5 Mark II",
	lens:"Sigma 150-600mm f5-6.3 (Contemporary)",
	tags:["Handheld"],
	caption:`This is my first good photo of a golden-crowned kinglet! I captured this little guy around an hour before sunset.`,
	filetype:"jpg",
	width:4892,
	height:3278,
},
{
	date:"2025-9-14",
	collections:["Featured Photos", "Wildlife Photography", "Nature Photography"],
	rating:5,
	title:"Cottontail Rabbit",
	subject:"Mountain cottontail (sylvilagus nuttallii)",
	location:"Sheridan Information Center and Rest Area, Wyoming, USA|https://maps.app.goo.gl/Dnv8rWvDZDpvgSW57|44.805626, -106.934790",
	shutterspeed:"1/125",
	aperture:"6.3",
	iso:"100",
	focallength:"600",
	camera:"Canon Rebel SL3",
	lens:"Sigma 150-600mm f5-6.3 (Contemporary)",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:3543,
	height:5225,
},
{
	date:"2025-5-25",
	collections:["Featured Photos", "Landscape Photography", "Nature Photography"],
	rating:5,
	title:"Smith Rock",
	subject:"",
	location:"Smith Rock State Park, Oregon, USA|https://maps.app.goo.gl/Maap4fuj8LBzjXsh8|44.371296, -121.137737",
	shutterspeed:"6",
	aperture:"",
	iso:"100",
	focallength:"11",
	camera:"Canon Rebel SL3",
	lens:"TTArtisan 11mm f2.8 Fisheye",
	tags:["ND filter"],
	caption:``,
	filetype:"jpg",
	width:3982,
	height:5873,
},
{
	date:"2025-5-24",
	collections:["Featured Photos", "Nature Photography"],
	rating:5,
	title:"Pillars of the Forest",
	subject:"Coast redwood (sequoia sempervirens)",
	location:"Oregon Redwoods, Oregon, USA|https://maps.app.goo.gl/PJjepuzKs2m92Spo6|42.011689, -124.149761",
	shutterspeed:"1/60",
	aperture:"2.8",
	iso:"100",
	focallength:"11",
	camera:"Canon Rebel SL3",
	lens:"TTArtisan 11mm f2.8 Fisheye",
	tags:["Handheld"],
	caption:`The size of the coast redwoods is truly majestic!`,
	filetype:"jpg",
	width:3610,
	height:5911,
},
{
	date:"2025-5-23",
	collections:["Featured Photos", "Landscape Photography", "Nature Photography"],
	rating:4,
	title:"Secret Beach",
	subject:"",
	location:"Secret Beach, Samuel H. Boardman Scenic Corridor, Oregon, USA|https://maps.app.goo.gl/JhdJwiUck2uSFYnH6|42.194014, -124.370857",
	shutterspeed:"20",
	aperture:"",
	iso:"100",
	focallength:"11",
	camera:"Canon Rebel SL3",
	lens:"TTArtisan 11mm f2.8 Fisheye",
	tags:["ND Filter"],
	caption:``,
	filetype:"jpg",
	width:5839,
	height:3689,
},
{
	date:"2025-5-21",
	collections:["Featured Photos", "Bird Photography", "Wildlife Photography", "Nature Photography"],
	rating:4.5,
	title:"Scanning the Surroundings",
	subject:"California quail (callipepla californica)",
	location:"William L. Finley National Wildlife Refuge, Oregon, USA|https://maps.app.goo.gl/38EJENE7pbWrmYaC9|44.418722, -123.324548",
	shutterspeed:"1/320",
	aperture:"6.3",
	iso:"100",
	focallength:"600",
	camera:"Canon Rebel SL3",
	lens:"Sigma 150-600mm f5-6.3 (Contemporary)",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:4906,
	height:3036,
},
{
	date:"2025-5-20",
	collections:["Featured Photos", "Nature Photography"],
	rating:4,
	title:"Flower Inspector",
	subject:"Bumblebee and foxglove",
	location:"Hatfield Marine Science Center, Oregon, USA|https://maps.app.goo.gl/qr29XvAyVALkKcon9|44.620553, -124.042092",
	shutterspeed:"1/500",
	aperture:"6.3",
	iso:"100",
	focallength:"600",
	camera:"Canon Rebel SL3",
	lens:"Sigma 150-600mm f5-6.3 (Contemporary)",
	tags:["Handheld"],
	caption:`I was photographing the flower but the looking back through my photos I realized I had been photo bombed by a bumblebee! Best photo bomb ever!`,
	filetype:"jpg",
	width:4083,
	height:2486,
},
{
	date:"2025-5-20",
	collections:["Featured Photos", "Bird Photography", "Wildlife Photography", "Nature Photography"],
	rating:4.8,
	title:"Bird of Gold",
	subject:"American Goldfinch (spinus tristis)",
	location:"Hatfield Marine Science Center, Oregon, USA|https://maps.app.goo.gl/k2uBb5uXPMBckHPZ9|44.620512, -124.042162",
	shutterspeed:"1/500",
	aperture:"6.3",
	iso:"100",
	focallength:"600",
	camera:"Canon Rebel SL3",
	lens:"Sigma 150-600mm f5-6.3 (Contemporary)",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:3791,
	height:2587,
},
{
	date:"2025-5-20",
	collections:["Featured Photos", "Nature Photography"],
	rating:3.5,
	title:"Turbulent Calm",
	subject:"",
	location:"Boiler Bay, Oregon, USA|https://maps.app.goo.gl/cZooy72dUoz4d7bW8|44.830037, -124.064889",
	shutterspeed:"1/2500",
	aperture:"5",
	iso:"100",
	focallength:"150",
	camera:"Canon Rebel SL3",
	lens:"Sigma 150-600mm f5-6.3 (Contemporary)",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:3564,
	height:5209,
},
{
	date:"2025-5-19",
	collections:["Featured Photos", "Landscape Photography", "Nature Photography"],
	rating:4,
	title:"Hug Point",
	subject:"",
	location:"Hug Point, Oregon, USA|https://maps.app.goo.gl/148kzgBYVvLs6FQW6|45.828123, -123.962741",
	shutterspeed:"3.2",
	aperture:"",
	iso:"100",
	focallength:"11",
	camera:"Canon Rebel SL3",
	lens:"TTArtisan 11mm f2.8 Fisheye",
	tags:["ND Filter"],
	caption:``,
	filetype:"jpg",
	width:5953,
	height:3802,
},
{
	date:"2025-5-18",
	collections:["Featured Photos", "Landscape Photography", "Nature Photography"],
	rating:4.5,
	title:"Multnomah Falls",
	subject:"",
	location:"Multnomah Falls, Oregon, USA|https://maps.app.goo.gl/gqmdA3y8MS5caLH26|45.576981, -122.116567",
	shutterspeed:"2",
	aperture:"",
	iso:"100",
	focallength:"11",
	camera:"Canon Rebel SL3",
	lens:"TTArtisan 11mm f2.8 Fisheye",
	tags:["ND Filter"],
	caption:``,
	filetype:"jpg",
	width:3306,
	height:5365,
},
{
	date:"2025-5-4",
	collections:["Featured Photos", "Macro Photography", "Nature Photography"],
	rating:4.8,
	title:"Micro Jungle Gym",
	subject:"Common dandelion (taraxacum officinale)",
	location:"Idaho, USA",
	shutterspeed:"1/160",
	aperture:"4",
	iso:"100",
	focallength:"55",
	camera:"Canon Rebel SL3",
	lens:"Canon EF-S 18-55mm f4-5.6",
	tags:["Extension tube", "Handheld"],
	caption:``,
	filetype:"jpg",
	width:4224,
	height:2598,
},
{
	date:"2024-12-1",
	collections:["Featured Photos", "Bird Photography", "Wildlife Photography", "Nature Photography"],
	rating:3.5,
	title:"Prepare for Touchdown",
	subject:"California gull (larus californicus)",
	location:"Coeur d'Alene Parkway State Park, Idaho, USA|https://maps.app.goo.gl/4uuGnEmvcgSyGZCF8|47.629390, -116.687694",
	shutterspeed:"1/800",
	aperture:"6.3",
	iso:"200",
	focallength:"600",
	camera:"Canon Rebel SL3",
	lens:"Sigma 150-600mm f5-6.3 (Contemporary)",
	tags:["Handheld"],
	caption:``,
	filetype:"png/jpg",
	width:3744,
	height:5225,
},
{
	date:"2024-6-19",
	collections:["Featured Photos", "Landscape Photography", "Nature Photography"],
	rating:4,
	title:"Miniature Mountain",
	subject:"",
	location:"Washington, USA",
	shutterspeed:"1/320",
	aperture:"5.6",
	iso:"100",
	focallength:"55",
	camera:"Canon Rebel SL3",
	lens:"Canon EF-S 18-55mm f4-5.6",
	tags:["Aerial", "Handheld"],
	caption:``,
	filetype:"png/jpg",
	width:6000,
	height:3664,
},
{
	date:"2024-6-4",
	collections:["Featured Photos", "Landscape Photography", "Nature Photography"],
	rating:4.5,
	title:"Lüderitz Coast",
	subject:"",
	location:"Lüderitz, Namibia|https://maps.app.goo.gl/gvgoBqyT3bdhhGYt5|-26.702792, 15.085847",
	shutterspeed:"1/2",
	aperture:"22",
	iso:"100",
	focallength:"18",
	camera:"Canon Rebel SL3",
	lens:"Canon EF-S 18-55mm f4-5.6",
	tags:[],
	caption:``,
	filetype:"jpg",
	width:5908,
	height:3664,
},
{
	date:"2024-5-28",
	collections:["Featured Photos", "Bird Photography", "Wildlife Photography", "Nature Photography"],
	rating:5,
	title:"Royal Pin",
	subject:"Pin-tailed Whydah (vidua macroura)",
	location:"Namibia",
	shutterspeed:"1/400",
	aperture:"6.3",
	iso:"100",
	focallength:"600",
	camera:"Canon Rebel SL3",
	lens:"Sigma 150-600mm f5-6.3 (Contemporary)",
	tags:["Handheld"],
	caption:``,
	filetype:"png/jpg",
	width:2808,
	height:4184,
},
{
	date:"2024-5-20",
	collections:["Featured Photos", "Landscape Photography", "Nature Photography"],
	rating:3.5,
	title:"African Sunset on the River",
	subject:"",
	location:"Namibia",
	shutterspeed:"1/50",
	aperture:"5.6",
	iso:"100",
	focallength:"18",
	camera:"Canon Rebel SL3",
	lens:"Canon EF-S 18-55mm f4-5.6",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:3798,
	height:5863,
},
{
	date:"2024-5-8",
	collections:["Featured Photos", "Wildlife Photography", "Nature Photography"],
	rating:4.5,
	title:"African Giant",
	subject:"African Bush Elephant (loxodonta africana)",
	location:"Etosha National Park, Namibia|https://maps.app.goo.gl/p5YXCwRgmHnEzLnQ9|-18.824934, 16.948363",
	shutterspeed:"1/2500",
	aperture:"5.6",
	iso:"400",
	focallength:"252",
	camera:"Canon Rebel SL3",
	lens:"Sigma 150-600mm f5-6.3 (Contemporary)",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:3813,
	height:5417,
},
{
	date:"2024-5-7",
	collections:["Featured Photos", "Bird Photography", "Wildlife Photography", "Nature Photography"],
	rating:3.5,
	title:"Blacksmith Lapwing",
	subject:"Blacksmith Lapwing (vanellus armatus)",
	location:"Etosha National Park, Namibia|https://maps.app.goo.gl/VFpke2LRTVna1JUd7|-18.858280, 16.924951",
	shutterspeed:"1/640",
	aperture:"6.3",
	iso:"400",
	focallength:"600",
	camera:"Canon Rebel SL3",
	lens:"Sigma 150-600mm f5-6.3 (Contemporary)",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:3535,
	height:5263,
},
{
	date:"2024-4-28",
	collections:["Featured Photos", "Wildlife Photography", "Nature Photography"],
	rating:5,
	title:"A Story of Battle",
	subject:"Lion (panthera leo)",
	location:"Etosha National Park, Namibia|https://maps.app.goo.gl/VyJBnRmLTGoTipiu7|-18.721645, 16.902001",
	shutterspeed:"1/250",
	aperture:"6.3",
	iso:"100",
	focallength:"500",
	camera:"Canon Rebel SL3",
	lens:"Sigma 150-600mm f5-6.3 (Contemporary)",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:4833,
	height:3048,
},
{
	date:"2024-4-28",
	collections:["Featured Photos", "Wildlife Photography", "Nature Photography"],
	rating:4,
	title:"Hello Zebra",
	subject:"Plains Zebra (equus quagga)",
	location:"Etosha National Park, Namibia|https://maps.app.goo.gl/Jgg13hb9bC7cfaSY6|-18.715218, 16.903733",
	shutterspeed:"1/800",
	aperture:"6.3",
	iso:"100",
	focallength:"500",
	camera:"Canon Rebel SL3",
	lens:"Sigma 150-600mm f5-6.3 (Contemporary)",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:2579,
	height:3567,
},
{
	date:"2024-4-28",
	collections:["Featured Photos", "Wildlife Photography", "Nature Photography"],
	rating:4,
	title:"Out on the Savanna",
	subject:"Plains Zebra (equus quagga)",
	location:"Etosha National Park, Namibia|https://maps.app.goo.gl/2QY2aj8AYvBWr4kHA|-18.785164, 16.908655",
	shutterspeed:"1/800",
	aperture:"6.3",
	iso:"100",
	focallength:"600",
	camera:"Canon Rebel SL3",
	lens:"Sigma 150-600mm f5-6.3 (Contemporary)",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:3747,
	height:5448,
},
{
	date:"2024-4-28",
	collections:["Featured Photos", "Wildlife Photography", "Nature Photography"],
	rating:4,
	title:"King of the Savanna",
	subject:"Lion (panthera leo)",
	location:"Etosha National Park, Namibia|https://maps.app.goo.gl/jk8YmaS7F4uDNU2DA|-18.827229, 16.950716",
	shutterspeed:"1/160",
	aperture:"6.3",
	iso:"100",
	focallength:"600",
	camera:"Canon Rebel SL3",
	lens:"Sigma 150-600mm f5-6.3 (Contemporary)",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:4344,
	height:2443,
},
{
	date:"2024-4-18",
	collections:["Featured Photos", "Landscape Photography", "Nature Photography"],
	rating:4.5,
	title:"African Sunset",
	subject:"",
	location:"Namibia",
	shutterspeed:"1/4000",
	aperture:"5",
	iso:"100",
	focallength:"150",
	camera:"Canon Rebel SL3",
	lens:"Sigma 150-600mm f5-6.3 (Contemporary)",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:4000,
	height:6000,
},
{
	date:"2024-4-13",
	collections:["Featured Photos", "Bird Photography", "Wildlife Photography", "Nature Photography"],
	rating:3.5,
	title:"Southern Cordonbleu",
	subject:"Southern Cordonbleu (uraeginthus angolensis)",
	location:"Namibia",
	shutterspeed:"1/640",
	aperture:"6.3",
	iso:"100",
	focallength:"600",
	camera:"Canon Rebel SL3",
	lens:"Sigma 150-600mm f5-6.3 (Contemporary)",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:3568,
	height:2008,
},
{
	date:"2024-4-12",
	collections:["Featured Photos", "Bird Photography", "Wildlife Photography", "Nature Photography"],
	rating:4,
	title:"Swainson's Spurfowl",
	subject:"Swainson's Spurfowl (pternistis swainsonii)",
	location:"Namibia",
	shutterspeed:"1/400",
	aperture:"6.3",
	iso:"100",
	focallength:"600",
	camera:"Canon Rebel SL3",
	lens:"Sigma 150-600mm f5-6.3 (Contemporary)",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:3736,
	height:2560,
},
{
	date:"2024-4-12",
	collections:["Featured Photos", "Bird Photography", "Wildlife Photography", "Nature Photography"],
	rating:4.5,
	title:"Laughing Dove",
	subject:"Laughing Dove (spilopelia senegalensis)",
	location:"Namibia",
	shutterspeed:"1/500",
	aperture:"6.3",
	iso:"125",
	focallength:"600",
	camera:"Canon Rebel SL3",
	lens:"Sigma 150-600mm f5-6.3 (Contemporary)",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:5216,
	height:2934,
},
{
	date:"2024-3-2",
	collections:["Featured Photos", "Bird Photography", "Wildlife Photography", "Nature Photography"],
	rating:4,
	title:"Red-breasted Nuthatch",
	subject:"Red-breasted Nuthatch (sitta canadensis)",
	location:"Idaho, USA",
	shutterspeed:"1/250",
	aperture:"6.3",
	iso:"1250",
	focallength:"600",
	camera:"Canon Rebel SL3",
	lens:"Sigma 150-600mm f5-6.3 (Contemporary)",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:5144,
	height:2894,
},
{
	date:"2024-3-1",
	collections:["Featured Photos", "Bird Photography", "Wildlife Photography", "Nature Photography"],
	rating:3.5,
	title:"Black-capped Chickadee",
	subject:"Black-capped Chickadee (poecile atricapillus)",
	location:"Idaho, USA",
	shutterspeed:"1/400",
	aperture:"6.3",
	iso:"640",
	focallength:"600",
	camera:"Canon Rebel SL3",
	lens:"Sigma 150-600mm f5-6.3 (Contemporary)",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:4081,
	height:2719,
},
{
	date:"2023-11-6",
	collections:["Featured Photos", "Landscape Photography", "Nature Photography"],
	rating:3.5,
	title:"Rain on the Lake",
	subject:"",
	location:"Washington, USA",
	shutterspeed:"1/80",
	aperture:"8",
	iso:"100",
	focallength:"18",
	camera:"Canon Rebel SL3",
	lens:"Canon EF-S 18-55mm f4-5.6",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:4000,
	height:6000,
},
{
	date:"2023-11-6",
	collections:["Featured Photos"],
	rating:4,
	title:"A-Frame Attic",
	subject:"",
	location:"Washington, USA",
	shutterspeed:"1/8",
	aperture:"8",
	iso:"400",
	focallength:"38",
	camera:"Canon Rebel SL3",
	lens:"Canon EF-S 18-55mm f4-5.6",
	tags:["Handheld"],
	caption:``,
	filetype:"png/jpg",
	width:3907,
	height:5998,
},
{
	date:"2023-10-21",
	collections:["Featured Photos", "Macro Photography", "Nature Photography"],
	rating:4.8,
	title:"Micro Golden Hour",
	subject:"",
	location:"Idaho, USA",
	shutterspeed:"1/6",
	aperture:"4",
	iso:"200",
	focallength:"55",
	camera:"Canon Rebel SL3",
	lens:"Canon EF-S 18-55mm f4-5.6",
	tags:["Extension tube", "Handheld"],
	caption:``,
	filetype:"png/jpg",
	width:3912,
	height:5936,
},
{
	date:"2023-10-21",
	collections:["Featured Photos", "Macro Photography", "Nature Photography"],
	rating:4,
	title:"Poky Planet",
	subject:"",
	location:"Idaho, USA",
	shutterspeed:"1/6",
	aperture:"4",
	iso:"160",
	focallength:"55",
	camera:"Canon Rebel SL3",
	lens:"Canon EF-S 18-55mm f4-5.6",
	tags:["Extension tube", "Handheld"],
	caption:``,
	filetype:"png/jpg",
	width:5099,
	height:2868,
},
{
	date:"2023-10-8",
	collections:["Featured Photos", "Landscape Photography", "Nature Photography"],
	rating:3.5,
	title:"Sunset Over the Mountains",
	subject:"",
	location:"Idaho, USA",
	shutterspeed:"1/200",
	aperture:"32",
	iso:"100",
	focallength:"170",
	camera:"Canon Rebel SL3",
	lens:"Canon EF 75-300mm f4-5.6",
	tags:["Handheld", "Panorama"],
	caption:``,
	filetype:"jpg",
	width:8283,
	height:2816,
},
{
	date:"2023-9-9",
	collections:["Featured Photos", "Macro Photography", "Nature Photography"],
	rating:4.5,
	title:"Lichen Monster",
	subject:"",
	location:"Idaho, USA",
	shutterspeed:"1/20",
	aperture:"4",
	iso:"320",
	focallength:"55",
	camera:"Canon Rebel SL3",
	lens:"Canon EF-S 18-55mm f4-5.6",
	tags:["Extension tube", "Handheld"],
	caption:``,
	filetype:"png/jpg",
	width:5952,
	height:3348,
},
{
	date:"2023-9-9",
	collections:["Featured Photos", "Macro Photography", "Nature Photography"],
	rating:4,
	title:"Liquid Gold",
	subject:"",
	location:"Idaho, USA",
	shutterspeed:"1/20",
	aperture:"4",
	iso:"160",
	focallength:"55",
	camera:"Canon Rebel SL3",
	lens:"Canon EF-S 18-55mm f4-5.6",
	tags:["Extension tube", "Handheld"],
	caption:``,
	filetype:"png/jpg",
	width:3619,
	height:5709,
},
{
	date:"2023-7-27",
	collections:["Featured Photos", "Macro Photography", "Nature Photography"],
	rating:4.8,
	title:"Real Abstract",
	subject:"",
	location:"Idaho, USA",
	shutterspeed:"1/40",
	aperture:"4",
	iso:"100",
	focallength:"55",
	camera:"Canon Rebel SL3",
	lens:"Canon EF-S 18-55mm f4-5.6",
	tags:["Extension tube", "Handheld"],
	caption:``,
	filetype:"jpg",
	width:3868,
	height:5527,
},
{
	date:"2023-7-14",
	collections:["Featured Photos", "Bird Photography", "Wildlife Photography", "Nature Photography"],
	rating:3.5,
	title:"I See You",
	subject:"",
	location:"Idaho, USA",
	shutterspeed:"1/500",
	aperture:"8",
	iso:"800",
	focallength:"220",
	camera:"Canon Rebel SL3",
	lens:"Canon EF 75-300mm f4-5.6",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:2340,
	height:3014,
},
{
	date:"2023-7-14",
	collections:["Featured Photos", "Bird Photography", "Wildlife Photography", "Nature Photography"],
	rating:4.5,
	title:"Ready for Breakfast",
	subject:"",
	location:"Idaho, USA",
	shutterspeed:"1/500",
	aperture:"8",
	iso:"400",
	focallength:"210",
	camera:"Canon Rebel SL3",
	lens:"Canon EF 75-300mm f4-5.6",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:5364,
	height:3017,
},
{
	date:"2023-7-27",
	collections:["Featured Photos", "Macro Photography", "Nature Photography"],
	rating:4.8,
	title:"Micro Monster",
	subject:"",
	location:"Idaho, USA",
	shutterspeed:"1/80",
	aperture:"4",
	iso:"400",
	focallength:"55",
	camera:"Canon Rebel SL3",
	lens:"Canon EF-S 18-55mm f4-5.6",
	tags:["Extension tube", "Handheld"],
	caption:``,
	filetype:"png/jpg",
	width:4569,
	height:2570,
},
{
	date:"2023-7-13",
	collections:["Featured Photos", "Bird Photography", "Wildlife Photography", "Nature Photography"],
	rating:3.5,
	title:"Hummingbird in Flight",
	subject:"",
	location:"Idaho, USA",
	shutterspeed:"1/320",
	aperture:"8",
	iso:"500",
	focallength:"205",
	camera:"Canon Rebel SL3",
	lens:"Canon EF 75-300mm f4-5.6",
	tags:["Handheld"],
	caption:``,
	filetype:"png/jpg",
	width:4224,
	height:2984,
},
{
	date:"2023-6-20",
	collections:["Featured Photos", "Macro Photography", "Nature Photography"],
	rating:3.5,
	title:"Hard Workers",
	subject:"",
	location:"Idaho, USA",
	shutterspeed:"1/250",
	aperture:"4",
	iso:"1000",
	focallength:"55",
	camera:"Canon Rebel SL3",
	lens:"Canon EF-S 18-55mm f4-5.6",
	tags:["Extension tube", "Handheld"],
	caption:``,
	filetype:"jpg",
	width:4104,
	height:2309,
},
{
	date:"2023-6-11",
	collections:["Featured Photos", "Wildlife Photography", "Nature Photography"],
	rating:3.5,
	title:"Prairie Dog",
	subject:"",
	location:"Giant Prairie Dog Statue, South Dakota, USA|https://maps.app.goo.gl/4xoArgddwNcJYZ7x9|43.822103, -101.900601",
	shutterspeed:"1/640",
	aperture:"8",
	iso:"160",
	focallength:"205",
	camera:"Canon Rebel SL3",
	lens:"Canon EF 75-300mm f4-5.6",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:3784,
	height:5527,
},
{
	date:"2023-6-10",
	collections:["Featured Photos", "Wildlife Photography", "Macro Photography", "Nature Photography"],
	rating:3.5,
	title:"Ready to Latch On",
	subject:"",
	location:"Necedah National Wildlife Refuge, Wisconsin, USA|https://maps.app.goo.gl/5JuCAcH856DHEeAt8|44.070196, -90.189198",
	shutterspeed:"1/640",
	aperture:"8",
	iso:"640",
	focallength:"220",
	camera:"Canon Rebel SL3",
	lens:"Canon EF 75-300mm f4-5.6",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:3492,
	height:2400,
},
{
	date:"2023-5-31",
	collections:["Featured Photos", "Wildlife Photography", "Nature Photography"],
	rating:3.5,
	title:"Snowshoe Hare",
	subject:"",
	location:"Idaho, USA",
	shutterspeed:"1/400",
	aperture:"8",
	iso:"2500",
	focallength:"205",
	camera:"Canon Rebel SL3",
	lens:"Canon EF 75-300mm f4-5.6",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:4000,
	height:6000,
},
{
	date:"2023-5-6",
	collections:["Featured Photos", "Macro Photography", "Nature Photography"],
	rating:4,
	title:"Magnifying Magnification",
	subject:"",
	location:"Idaho, USA",
	shutterspeed:"1/200",
	aperture:"4",
	iso:"250",
	focallength:"55",
	camera:"Canon Rebel SL3",
	lens:"Canon EF-S 18-55mm f4-5.6",
	tags:["Extension tube", "Handheld"],
	caption:``,
	filetype:"png/jpg",
	width:3487,
	height:4752,
},
{
	date:"2023-4-15",
	collections:["Featured Photos", "Wildlife Photography", "Macro Photography", "Nature Photography"],
	rating:4.5,
	title:"Hold Still",
	subject:"",
	location:"Idaho, USA",
	shutterspeed:"1/800",
	aperture:"4",
	iso:"400",
	focallength:"55",
	camera:"Canon Rebel SL3",
	lens:"Canon EF-S 18-55mm f4-5.6",
	tags:["Extension tube", "Handheld"],
	caption:``,
	filetype:"jpg",
	width:3678,
	height:2069,
},
{
	date:"2023-4-8",
	collections:["Featured Photos", "Wildlife Photography", "Macro Photography", "Nature Photography"],
	rating:4.8,
	title:"STAREDOWN",
	subject:"",
	location:"Idaho, USA",
	shutterspeed:"1/20",
	aperture:"4",
	iso:"800",
	focallength:"55",
	camera:"Canon Rebel SL3",
	lens:"Canon EF-S 18-55mm f4-5.6",
	tags:["Extension tube", "Handheld"],
	caption:``,
	filetype:"png/jpg",
	width:4984,
	height:2804,
},
{
	date:"2022-11-24",
	collections:["Featured Photos", "Nature Photography"],
	rating:4,
	title:"Autumn Color",
	subject:"",
	location:"Idaho, USA",
	shutterspeed:"1/160",
	aperture:"6.5",
	iso:"160",
	focallength:"215",
	camera:"Canon PowerShot SX530 HS",
	lens:"",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:2255,
	height:3015,
},
{
	date:"2022-9-7",
	collections:["Featured Photos", "Landscape Photography", "Nature Photography"],
	rating:4.8,
	title:"Day to Night",
	subject:"",
	location:"Idaho, USA",
	shutterspeed:"1/1000",
	aperture:"4",
	iso:"125",
	focallength:"7",
	camera:"Canon PowerShot SX530 HS",
	lens:"",
	tags:["Handheld"],
	caption:`Stars added in post.`,
	filetype:"jpg",
	width:3272,
	height:4408,
},
{
	date:"2022-8-31",
	collections:["Featured Photos", "Nature Photography"],
	rating:4,
	title:"Electric Sky",
	subject:"",
	location:"Idaho, USA",
	shutterspeed:"1/60",
	aperture:"2.2",
	iso:"",
	focallength:"3.7",
	camera:"Canon XA40",
	lens:"",
	tags:["Stacked (30)"],
	caption:`Stacked from 30 frames (1 second) of 4K video.`,
	filetype:"png/jpg",
	width:3840,
	height:2160,
},
{
	date:"2022-5-2",
	collections:["Featured Photos", "Wildlife Photography", "Macro Photography", "Nature Photography"],
	rating:4.5,
	title:"Micro Alien",
	subject:"",
	location:"Idaho, USA",
	shutterspeed:"1/50",
	aperture:"4.5",
	iso:"200",
	focallength:"10",
	camera:"Canon PowerShot SX530 HS",
	lens:"",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:3021,
	height:1700,
},
{
	date:"2022-3-22",
	collections:["Featured Photos", "Bird Photography", "Wildlife Photography", "Nature Photography"],
	rating:4,
	title:"Dark-eyed Junco",
	subject:"Dark-eyed Junco (junco hyemalis)",
	location:"Idaho, USA",
	shutterspeed:"1/160",
	aperture:"6.5",
	iso:"320",
	focallength:"215",
	camera:"Canon PowerShot SX530 HS",
	lens:"",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:2414,
	height:3016,
},
{
	date:"2022-2-11",
	collections:["Featured Photos", "Nature Photography"],
	rating:3.5,
	title:"Crusted Snow",
	subject:"",
	location:"Idaho, USA",
	shutterspeed:"1/50",
	aperture:"4.5",
	iso:"800",
	focallength:"12",
	camera:"Canon PowerShot SX530 HS",
	lens:"",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:2513,
	height:3456,
},
{
	date:"2022-2-2",
	collections:["Featured Photos", "Macro Photography", "Nature Photography"],
	rating:3.5,
	title:"One Among Many",
	subject:"",
	location:"Idaho, USA",
	shutterspeed:"1/50",
	aperture:"4.5",
	iso:"200",
	focallength:"13",
	camera:"Canon PowerShot SX530 HS",
	lens:"",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:3200,
	height:1800,
},
{
	date:"2021-11-22",
	collections:["Featured Photos", "Macro Photography", "Nature Photography"],
	rating:4.5,
	title:"Sunrise on a Tiny Planet",
	subject:"",
	location:"Idaho, USA",
	shutterspeed:"1/250",
	aperture:"4.5",
	iso:"100",
	focallength:"12",
	camera:"Canon PowerShot SX530 HS",
	lens:"",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:4608,
	height:2592,
},
{
	date:"2021-12-28",
	collections:["Featured Photos", "Nature Photography"],
	rating:4,
	title:"Hello Stickman",
	subject:"",
	location:"Idaho, USA",
	shutterspeed:"1/640",
	aperture:"6.5",
	iso:"400",
	focallength:"215",
	camera:"Canon PowerShot SX530 HS",
	lens:"",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:3456,
	height:4608,
},
{
	date:"2021-12-19",
	collections:["Featured Photos", "Nature Photography"],
	rating:3.5,
	title:"Snowy Slope",
	subject:"",
	location:"Idaho, USA",
	shutterspeed:"1/160",
	aperture:"6.5",
	iso:"160",
	focallength:"215",
	camera:"Canon PowerShot SX530 HS",
	lens:"",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:4608,
	height:2592,
},
{
	date:"2021-11-16",
	collections:["Featured Photos", "Landscape Photography", "Nature Photography"],
	rating:4,
	title:"Deadly Atmosphere",
	subject:"",
	location:"Idaho, USA",
	shutterspeed:"1/125",
	aperture:"5.6",
	iso:"640",
	focallength:"121",
	camera:"Canon PowerShot SX530 HS",
	lens:"",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:2257,
	height:3007,
},
{
	date:"2021-11-9",
	collections:["Featured Photos", "Nature Photography"],
	rating:3.5,
	title:"Sunlight After Rain",
	subject:"",
	location:"Idaho, USA",
	shutterspeed:"1/125",
	aperture:"5.6",
	iso:"320",
	focallength:"107",
	camera:"Canon PowerShot SX530 HS",
	lens:"",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:3320,
	height:4296,
},
{
	date:"2021-9-14",
	collections:["Featured Photos", "Macro Photography", "Nature Photography"],
	rating:4,
	title:"Crash Landing",
	subject:"",
	location:"Idaho, USA",
	shutterspeed:"1/125",
	aperture:"4.5",
	iso:"100",
	focallength:"12",
	camera:"Canon PowerShot SX530 HS",
	lens:"",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:3016,
	height:3776,
},
{
	date:"2021-9-14",
	collections:["Featured Photos", "Macro Photography", "Nature Photography"],
	rating:4,
	title:"Dew Decoration",
	subject:"",
	location:"Idaho, USA",
	shutterspeed:"1/50",
	aperture:"4.5",
	iso:"100",
	focallength:"12",
	camera:"Canon PowerShot SX530 HS",
	lens:"",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:2172,
	height:3054,
},
{
	date:"2021-8-24",
	collections:["Featured Photos", "Wildlife Photography", "Nature Photography"],
	rating:3.5,
	title:"KEEP OUT",
	subject:"",
	location:"Idaho, USA",
	shutterspeed:"1/25",
	aperture:"4.5",
	iso:"800",
	focallength:"12",
	camera:"Canon PowerShot SX530 HS",
	lens:"",
	tags:[],
	caption:``,
	filetype:"jpg",
	width:3916,
	height:2585,
},
{
	date:"2021-7-9",
	collections:["Featured Photos", "Bird Photography", "Wildlife Photography", "Nature Photography"],
	rating:4.5,
	title:"Evening Reflection",
	subject:"",
	location:"Idaho, USA",
	shutterspeed:"1/160",
	aperture:"6.5",
	iso:"125",
	focallength:"215",
	camera:"Canon PowerShot SX530 HS",
	lens:"",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:2720,
	height:2480,
},
{
	date:"2021-6-13",
	collections:["Featured Photos", "Bird Photography", "Wildlife Photography", "Nature Photography"],
	rating:3.5,
	title:"Not the Best Singer",
	subject:"Juvenile Pileated Woodpecker (dryocopus pileatus)",
	location:"Idaho, USA",
	shutterspeed:"1/800",
	aperture:"6.5",
	iso:"100",
	focallength:"215",
	camera:"Canon PowerShot SX530 HS",
	lens:"",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:3264,
	height:1836,
},
{
	date:"2021-5-28",
	collections:["Featured Photos", "Nature Photography"],
	rating:4,
	title:"Basic Backdrop",
	subject:"Thimbleberry (rubus parviflorus)",
	location:"Idaho, USA",
	shutterspeed:"1/50",
	aperture:"4.5",
	iso:"160",
	focallength:"15",
	camera:"Canon PowerShot SX530 HS",
	lens:"",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:4357,
	height:3165,
},
{
	date:"2020-10-28",
	collections:["Featured Photos", "Nature Photography"],
	rating:4,
	title:"Golden Decoration",
	subject:"Quaking Aspen (populus tremuloides)",
	location:"Idaho, USA",
	shutterspeed:"1/160",
	aperture:"6.5",
	iso:"125",
	focallength:"215",
	camera:"Canon PowerShot SX530 HS",
	lens:"",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:4608,
	height:2592,
},
{
	date:"2020-6-6",
	collections:["Featured Photos", "Nature Photography"],
	rating:4.5,
	title:"Let Your Light Shine",
	subject:"Tall Buttercup (ranunculus acris)",
	location:"Idaho, USA",
	shutterspeed:"1/200",
	aperture:"6.5",
	iso:"100",
	focallength:"215",
	camera:"Canon PowerShot SX530 HS",
	lens:"",
	tags:["Handheld"],
	caption:``,
	filetype:"png/jpg",
	width:3284,
	height:4187,
},
{
	date:"2020-4-21",
	collections:["Featured Photos", "Bird Photography", "Wildlife Photography", "Nature Photography"],
	rating:4,
	title:"Rufous Hummingbird",
	subject:"Rufous Hummingbird (selasphorus rufus)",
	location:"Idaho, USA",
	shutterspeed:"1/160",
	aperture:"6.5",
	iso:"100",
	focallength:"215",
	camera:"Canon PowerShot SX530 HS",
	lens:"",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:3456,
	height:4256,
},
{
	date:"2020-4-21",
	collections:["Featured Photos", "Bird Photography", "Wildlife Photography", "Nature Photography"],
	rating:4.5,
	title:"Poky Perch",
	subject:"Rufous Hummingbird (selasphorus rufus)",
	location:"Idaho, USA",
	shutterspeed:"1/200",
	aperture:"6.5",
	iso:"100",
	focallength:"215",
	camera:"Canon PowerShot SX530 HS",
	lens:"",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:4608,
	height:2592,
},
{
	date:"2020-4-21",
	collections:["Featured Photos", "Bird Photography", "Wildlife Photography", "Nature Photography"],
	rating:4,
	title:"American Robin",
	subject:"American Robin (turdus migratorius)",
	location:"Idaho, USA",
	shutterspeed:"1/160",
	aperture:"6.5",
	iso:"500",
	focallength:"215",
	camera:"Canon PowerShot SX530 HS",
	lens:"",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:2638,
	height:3548,
},
{
	date:"2020-1-15",
	collections:["Featured Photos", "Nature Photography"],
	rating:4,
	title:"Morning Dusting",
	subject:"",
	location:"Idaho, USA",
	shutterspeed:"1/640",
	aperture:"5",
	iso:"100",
	focallength:"27",
	camera:"Canon PowerShot SX530 HS",
	lens:"",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:2968,
	height:4320,
},
{
	date:"2019-4-24",
	collections:["Featured Photos", "Wildlife Photography", "Nature Photography"],
	rating:4,
	title:"Blending In",
	subject:"",
	location:"Idaho, USA",
	shutterspeed:"1/200",
	aperture:"6.5",
	iso:"400",
	focallength:"215",
	camera:"Canon PowerShot SX530 HS",
	lens:"",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:4190,
	height:2645,
},
{
	date:"2016-5-27",
	collections:["Featured Photos", "Wildlife Photography", "Macro Photography", "Nature Photography"],
	rating:3.5,
	title:"Mossy Grave",
	subject:"",
	location:"",
	shutterspeed:"",
	aperture:"",
	iso:"",
	focallength:"",
	camera:"Canon PowerShot SX110 IS",
	lens:"",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:3000,
	height:1688,
},
{
	date:"2014-9-10",
	collections:["Featured Photos", "Nature Photography"],
	rating:3.5,
	title:"TORRENT",
	subject:"",
	location:"Yellowstone National Park, Wyoming, USA|https://maps.app.goo.gl/bSngv31mg6hwamq38|45.004612, -110.692066",
	shutterspeed:"1/200",
	aperture:"6.9",
	iso:"100",
	focallength:"25",
	camera:"Canon PowerShot A2300",
	lens:"",
	tags:["Handheld"],
	caption:``,
	filetype:"jpg",
	width:4608,
	height:3006,
},
]